import type { HttpContext } from '@adonisjs/core/http'
import type { NextFn } from '@adonisjs/core/types/http'
import cache from '@adonisjs/cache/services/main'
import env from '#start/env'
import { parse } from 'node-html-parser'
import app from '@adonisjs/core/services/app'
import crypto from 'node:crypto'

export const md5 = (toEncode: any): string => {
  return crypto.createHash('md5').update(toEncode.toString()).digest('hex') // Create a hash based on the page content
}

const config = {
  serverCache: app.inProduction,
}

export default class HtmxMiddleware {
  async handle(ctx: HttpContext, next: NextFn) {
    /** Check if we will return components or the whole page? */
    let isHTMLXRequest = false
    let targets: string | undefined

    let cacheKey: string | undefined
    const headers = ctx.request.headers()

    if ('hx-request' in headers && !('hx-boosted' in headers)) {
      isHTMLXRequest = true

      // A specific target has been selected
      if ('hx-target' in headers) {
        targets = `#${headers['hx-target']!.toString()}`
      } // TODO: What about hx-target-error

      // Specific out of bounds headers have been requested
      if (ctx.request.qs()['elements']) {
        targets = ctx.request.qs()['elements']
      }
    }
    if (
      config.serverCache &&
      env.get('NODE_ENV') !== 'development' &&
      !('hx-no-cache' in headers)
    ) {
      // Don't cache during development
      cacheKey = md5(ctx.route?.pattern || '' + targets)
      const cachedHTML = await cache.get(cacheKey)
      if (cachedHTML) {
        // End request here so we don't end up building the template again
        return ctx.response.status(200).send(cachedHTML)
      }
    }

    /**
     * Call next method in the pipeline and return its output
     */

    // use AST to process the rendered output generated by edge and only return the @mata component requested
    await next()

    const response = ctx.response
    const responseHeaders = ctx.response.getHeaders()
    if ('location' in responseHeaders && isHTMLXRequest) {
      // If Adonis has requested a page redirect, we should do it the "HTMX way"
      return response.removeHeader('location').append('hx-redirect', responseHeaders.location!)
    }
    if (
      response.getStatus() >= 200 &&
      response.getStatus() < 300 &&
      response.hasContent &&
      isHTMLXRequest &&
      !('hx-redirect' in responseHeaders) && // If we are redirecting we don't mess with the response
      (!('content-type' in responseHeaders) ||
        responseHeaders['content-type'] !== 'application/json') // Check if 'content-type' exists and is not 'application/json'
    ) {
      // Set the page URL path
      // response.header('Hx-Push-Url', ctx.request.url()) // Now doing this via the client
      let html = ''
      const page = parse(response.content![0])
      const title = page.querySelector('title')
      // Only send the data element if title/description fields require updating
      if (title) {
        html += `<title>${title.innerText}</title>`
      }
      let components = ''

      if (targets) {
        targets.split(',').forEach((target) => {
          components += page.querySelector(target)?.removeWhitespace().toString() || ''
        })
        response.header('HX-Reselect', targets)
      }

      html += components

      if (
        config.serverCache &&
        ctx.request.method() === 'GET' && // We don't want to cache data that can send validation etc. like POST
        env.get('NODE_ENV') !== 'development' &&
        !('hx-no-cache' in headers)
      ) {
        if (cacheKey) {
          await cache.set(cacheKey, html)
        }
      }

      return response.send(html)
    }

    return response
  }
}
